---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1flp3w5drsleuca86tgf5a74hj2ttp56xxrjtge2zvqhmf0xpjcfsj80j7x
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1flp3w5drsleuca86tgf5a74hj2ttp56xxrjtge2zvqhmf0xpjcfsj80j7x
