# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:sdeL6XsPw7hZyXDSQGWS2NdIuaXs07KRYw==,iv:5EZTe3ykZZ2eDiMuHFN1Jnr6Awx1QvacUEU5kRBQcW8=,tag:TsaplHa5uwFTdpbM6E+VKw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:iKBKRb2lXauV3Bs0veCQ1U8UsHWJQme85D1O2jEFs3aYPvuzyg==,iv:e0IGN3sSbSvOs/P96RcuhTA3LMO4YtvTguXFogabGWg=,tag:mA/wJU8KA94TEI9oTpsRCg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:SPiyxfrQOz6I0/pZlaDJ,iv:TNsFt7sXmeqgMeu8O7mJqBtDk/Wt94/kX0DFDk2UbaM=,tag:pO4bRYo5m7T1n8qflsxP1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1flp3w5drsleuca86tgf5a74hj2ttp56xxrjtge2zvqhmf0xpjcfsj80j7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK1JqdkIxVVIxVjRFVFlG
            VlZpalg4MnJ5WlJ3WGJFSWlsUEt2a1VXT0JVCmp5MmpNbkhkV1gwdmYyQjZHNloy
            ems1QlZLeklvNFUzOTJOTFdQV1QzK2sKLS0tIHFCclIraWwwQWZlRmo2VENDWGJ6
            OUs2aTNLWC9GZmY4YW4weEYxVzd6R3cKnieMpFdC79K9be98ub6yj7z5eNqJgpcG
            h6mGtBds2nDfBx25JmAVa1G50k8KSBFvit06M5oanJN+Wq93UBJ2eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-26T15:54:44Z"
    mac: ENC[AES256_GCM,data:4Y7kLJI3XOgjdn8TI0cTYuqM8TRL2mxtAnGfLU7kVD7sj7BRg2y9waoXWqP13+68AFktNjyhSWj/MURy6ZuQcQPmY3yTT7jmOtdpK0pFGL1ujvzg8u1lHps9c1gvEo1n4F3aej3+vfHRIXRA8L+UsEzyW+62PjT2su95uPznD+4=,iv:nper4rz7skziKqogPnJdVcYhcjNtI6kBgqylXmoJy64=,tag:A4TrnNVvBon4ChZO4XNM7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
