---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Etc/Rome
  METALLB_LB_RANGE: 10.0.0.111-10.0.0.120
  METALLB_K8S_GATEWAY_ADDR: 10.0.0.111
  METALLB_INGRESS_ADDR: 10.0.0.112
