# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:PqCGnPKknaHxng==,iv:oh7CQ1PTm7AO77RE0YKwg4LCMnmAQfC9Huj6OHBgdGQ=,tag:s4x9//jaw+Ou/jT4GeZJ6A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:vd35V3Ke7VOe8WMEifKDyliZTgLvgUu4RA==,iv:CYPOby+Ch0W22THMOvBZg+j6fRysFEhLgq6h7r/1+u0=,tag:yr/1tcHbJG68OGoaPpJaMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1flp3w5drsleuca86tgf5a74hj2ttp56xxrjtge2zvqhmf0xpjcfsj80j7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTWtZaEthd0xPVzZQZ05D
            NDJsNytFeDBnbi9kT3gyclQyMzc4VExjZGhVClNwcTNabUFBVkJQdnVkRkZGRk1S
            U2g1NDcvMm4xQjRYUlhZUmNCK0xTN2cKLS0tIGhwRlJoT3hzTE5zcmlFUmtOVzRV
            WDg1Ty9HRDhaS1hwQ21pYjZHNmJMaXMKtJCR7ESJdCuSN+T5H5L9l6k50Q0hNyzq
            C5O850JL8R2Ndcu9qWlp5j5dDmWUJ44eLdX0B45BvQF6EpheuEqQ7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-09T16:51:56Z"
    mac: ENC[AES256_GCM,data:deU3Vz33uSi9mFhz8ZPv8Ndlv0UwQ9cb0MSbw4HrKX2fmlLsO41YzNQa8NgtJ6fZfSk4Kyid8slGTyJOd7+mbEylFkVcTT+lsaLU9VdNwTm0nuBS9Hzh2mOATeEyjajSZLP7rhp/U031iuTUFBccou3pDhbf6GxCBXeUthd2ess=,iv:DqRuPSeJ4kjiEDjduBUVXW4staP0IiwMaKpgeAsjqpg=,tag:GA+I/DdKwMk98roMK38DzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
