kind: Secret
ansible_user: ENC[AES256_GCM,data:Y3vF5eqK,iv:gfHsv2ARCxPOMhpuQOa7btM0lgmhwSkOtAh4x593/2o=,tag:hvP42+GQv07erDobRmhrvw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ROEa2YnZnpr6Jw==,iv:R/9VJtit10+n2gmaiWCi3RhO9GhlFIBuTsrofTuZrJQ=,tag:hkBqI+w5PTjr9LM59ENE6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1flp3w5drsleuca86tgf5a74hj2ttp56xxrjtge2zvqhmf0xpjcfsj80j7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUVdIeWpqQlBhc09nUWpX
            SU5BcXQyMFZnWm9JY2JWbXRSckpkWVIrdVRVCmU2TUR0Qkt5U0tkZktha2FPamZL
            bk83Q3BwS3FtTTNHVVN1Yzc5blRTcGMKLS0tIHFRTldCMnU0N0djVDI4TnZNbUR3
            ck5YQ3FVZDlSZDlBcDhhU0Q4Qmc2U1kKx0OMaLUinfL7V0aFJGr70p3nbBT5u6MQ
            RQi7utbqojzwzYEnzuK4nKAmgAkDqWMuQw7TDAkrrqD1j5r01suJ3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-09T16:51:57Z"
    mac: ENC[AES256_GCM,data:3J+cFo2WAjEzXpaJY4DhxZyo8nIqP07Z+G4FH2S92wkjv3MxdxUUbHdt8S2uMMaEu8Q/4riRdla+kCCPzZLgdZ4Qae2jFarZNO3SJU2YagqB7sY5snFLL16MjdtNDtlN7MOTuJ8Sbvg8ERrVgLcW1KvwwfOL8aPOgp30oBYuOY4=,iv:R/MSZwbtqE/K20VetRqngnDTMjva2a/7PBLVBIBTnF0=,tag:6xbH+0vYVE3s77zIOhH7Hg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
