kind: Secret
ansible_user: ENC[AES256_GCM,data:drDKecq8,iv:a84Ovyd4FREY1+RhGxSH6O/pAA3fMmwN6hG6+zjPgE0=,tag:zCWd968OkKiGUjmlq/8AJg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:e6+9CKQ7f+unmA==,iv:6deqH3CC92KBGKhvBzAEEMcFWUP0NJCy5j843osxG3c=,tag:pYG0SzRi7plsXD7IDHWCaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1flp3w5drsleuca86tgf5a74hj2ttp56xxrjtge2zvqhmf0xpjcfsj80j7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUlmVGZ3a3N4VEc4ODli
            RWVGbjJNbHVLd1Y5dkVyYTRleERRWlV1WkhzCi9rNHpFLzVXYWR6WkhBTzN0TjJP
            bytpWUVLL2FIMTdrWmdTQkQ2bTl1QUUKLS0tIEFGTHdHS3VqYXEyQ2p4aG02WUdQ
            L3BvMUVMWlczOGxkUGFKQTJybmYveTgKKSI2uyUdeDZwYK5wiqNJsh2c/Kz9hZH4
            MHxFYHhK68TIZtfZsx4nyb5BBTZc1k3PMq5CNE0hZVixFs5g6I8XxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-26T10:05:45Z"
    mac: ENC[AES256_GCM,data:b+sfZyvzofe9/Wz4695zNR7KAVWhXBlut3zZ1n8wql7dNV2GC6fqyLagyehGtTR0KaUZJyH7xGsh2DbcoROv6VkNYjo21R3AXSoQKxWlOw++My+0iax0vPDR0CPYeGa5XvijNBL2o25VK6oxUJ7Rm/yXGbGOGOBqQPPxL5r3SYw=,iv:pCjIhU2kaiK6066Qfou5mxUDU7t0eS8tMLaNpiejIt4=,tag:Xn5TUG7goNh9D3+K0QPIBA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
